repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: cpp-linter-lib/tests/capture_tools_output/cpp-linter/cpp-linter/test_git_lib.patch
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
        args: [--maxkb=9000]
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      # Run the python linter.
      - id: ruff
        args: [ --fix ]
      # Run the python formatter.
      - id: ruff-format
