version: "0.2"
language: en
words:
  - binstall
  - Boolish
  - bugprone
  - chrono
  - codecov
  - consts
  - cppcoreguidelines
  - cstdio
  - Doherty
  - endgroup
  - Falsey
  - gitmodules
  - iomanip
  - libgit
  - markdownlint
  - maturin
  - mdbook
  - msvc
  - napi
  - nonminimal
  - peekable
  - posix
  - preprocess
  - pybind
  - pyfunction
  - pymodule
  - pypi
  - pyproject
  - ratelimit
  - reqwest
  - revparse
  - tempdir
  - tempfile
  - vararg
  - venv
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - target/**
