version: "0.2"
language: en
words:
  - bugprone
  - consts
  - cppcoreguidelines
  - endgroup
  - Falsey
  - gitmodules
  - iomanip
  - libgit
  - nonminimal
  - peekable
  - posix
  - pybind
  - pyfunction
  - pymodule
  - reqwest
  - revparse
  - tempdir
  - tempfile
  - venv
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - target/**
