[package]
name = "cpp-linter"
edition = "2021"
readme = "README.md"
keywords = ["clang-tidy", "clang-format", "linter"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
repository = "https://github.com/cpp-linter/cpp-linter-rs"
version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
clap = "4.5.20"
colored = "2.1.0"
fast-glob = "0.4.0"
futures = "0.3.31"
git2 = "0.19.0"
lenient_semver = "0.4.2"
log = { version = "0.4.22", features = ["std"] }
openssl = { version = "0.10", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1", optional = true }
regex = "1.11.1"
reqwest = "0.12.9"
semver = "1.0.23"
serde = { version = "1.0.215", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"]}
tokio-macros = "2.4.0"
tokio-stream = "0.1.16"
which = "7.0.0"

[dev-dependencies]
mockito = "1.5.0"
tempfile = "3.14.0"

[features]
openssl-vendored = ["dep:openssl", "dep:openssl-probe"]

[[bin]]
name = "cpp-linter"
path = "src/main.rs"
test = false
bench = false
