name: Binary executable builds

permissions:
  contents: read

on:
  push:
    branches: [main]
    tags:
      - v[0-9]+.*
  pull_request:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:

  create-assets:
    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            vendered: false
            cross: false
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: arm-unknown-linux-gnueabi
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: powerpc-unknown-linux-gnu
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: powerpc64-unknown-linux-gnu
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: powerpc64le-unknown-linux-gnu
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: s390x-unknown-linux-gnu
            os: ubuntu-latest
            vendered: true
            cross: true
          - target: aarch64-apple-darwin
            os: macos-latest
            vendered: true
            cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            vendered: true
            cross: false
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            vendered: false
            cross: false
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            vendered: false
            cross: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          python-version: '3.x'

      - name: Increment version
        if: startsWith(github.ref, 'refs/tags/')
        run: python .github/workflows/replace_version_spec.py --new-version=${{ github.ref_name }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install cross (cargo cross compiler)
        if: matrix.cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build (native)
        if: ${{ !matrix.cross }}
        run: cargo build --manifest-path cpp-linter-lib/Cargo.toml --release --bin cpp-linter --target ${{ matrix.target }} ${{ matrix.vendered && '--features openssl-vendored' || '' }}

      - name: Build (cross)
        if: matrix.cross
        run: cross build --manifest-path cpp-linter-lib/Cargo.toml --release --bin cpp-linter --target ${{ matrix.target }} ${{ matrix.vendered && '--features openssl-vendored' || '' }}

      - name: Prepare artifacts
        run: mv target/${{ matrix.target }}/release/cpp-linter${{ runner.os == 'Windows' && '.exe' || '' }} ./cpp-linter-${{ matrix.target }}${{ runner.os == 'Windows' && '.exe' || '' }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpp-linter-${{ matrix.target }}
          path: cpp-linter-${{ matrix.target }}*
          if-no-files-found: error

  create-release:
    if: startswith(github.ref, 'refs/tagsv')
    runs-on: ubuntu-latest
    needs: [create-assets]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable --no-self-update
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Increment version
        run: python .github/workflows/replace_version_spec.py --new-version=${{ github.ref_name }}
      - run: cargo package
      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          pattern: cpp-linter-*
          path: dist
      - name: Create a Github Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(ls dist/cpp-linter*
          gh release create ${{ github.ref_name }} --generate-notes $files
      - run: cargo publish
        working-directory: cpp-linter-lib
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
