name: Pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: cpp-linter/.github/.github/workflows/pre-commit.yml@main

  cargo-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - name: cargo clippy
        run: cargo clippy
      - name: cargo fmt
        run: cargo fmt --check
