name: Pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: cpp-linter/.github/.github/workflows/pre-commit.yml@main

  cargo-tools:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - name: Cache .cargo locked resources
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: cargo clippy
        run: cargo clippy
      - name: cargo fmt
        run: cargo fmt --check
